### ISSUE TITLE
Add a shortcut / command for hiding fman (Like OS X's Cmd+H)

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#101]

**Comment by macosxguru** [comment]
The system adds this to every application. 
⌘+H hides the application. 
⌥⌘ + H hides all other applications.

It is operational in fman on the Mac, too. 

You are thinking of adding it to the other platforms?

macosxguru

**Comment by mherrmann** [comment]
Hm, you're right. I thought this was broken. I just asked the user who requested this for clarification.

**Comment by mherrmann** [comment]
There was a miscommunication with the user. Hiding works as expected.

The first closed issue! ;)
