### ISSUE TITLE
fman sometimes crashes on close

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#102]
At least some of the crashes seem to be caused by a [bug in Qt](https://bugreports.qt.io/browse/QTBUG-54663).

**Comment by courtagenjim** [comment]
Reproduced here. Fman v0.3.6; OSX Yosemite (v10.10.5)

**INTERMITTENT**

**Comment by mherrmann** [comment]
Thanks! I'm already working on this and hope to have a fix for the most frequent cause of the crashes in the coming days.

**Comment by mherrmann** [comment]
Fixed in v0.3.7.
