### ISSUE TITLE
Make it possible to install plugins from GitHub

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#103]

**Comment by kek91** [comment]
Will the plugin manager/installer also be able to handle plugin updates? Could be solved by requiring every plugin repo to have a `package.json` or similiar file with the required information.

**Comment by macosxguru** [comment]
It will be a lot more useful if the plugin manager/installer does do updates. 

Good idea.

macosxguru

**Comment by mherrmann** [comment]
Very good question. Not in the beginning. But ideally, I'd like to make it so fman has the necessary information - without requiring plugin developers to include something like a `package.json`.

Here's what I envision: In addition to folders in the `{data dir.}/Plugins/` folder, you can also have .zip files - for plugins which you didn't create yourself but downloaded from the internet. The version could be encoded in the name of the zip file. Eg: `StatusBarExtended-v0.1.0.zip`. To see whether a plugin has to be updated, fman could look at the file name, see "I have v0.1.0", query GitHub if there are newer releases, and if yes install them.

It would also be cool to have a `Plugins.json` file which (say) you can take from one machine to another to quickly install the plugins you always have. This file could also contain information about specific versions you want. Say you want StatusBarExtended 0.1.0 but not 0.2.0. Then you might be able to specify this in the `Plugins.json` file.

**Comment by kek91** [comment]
Indeed that would also work for managing updates.

I didn't mention it earlier, but `package.json` could also hold other useful meta data like author, description, dependencies(?), compatible with fman vx.x.x, etc. 
This is useful information which I feel should be presented in your Plugin Manager *, and if we don't have a common way to store this info you'll have to keep track of this yourself (and we will have to nag you if any of that information changes).

*) Don't get me wrong, starting out with a simple downloader is fantastic, much better than manually downloading tons of repositories out there. You can gradually evolve this into a more sophisticated manager later :)

**Comment by mherrmann** [comment]
Yes you are right, `Plugin.json` would be useful (I think I prefer `Plugin.json` or `plugin.json` because they're called fman plugins. Not packages, or extensions or...). I assume it will be added in the future for precisely the infos you said. But it would be cool if it were not _required_ even then, to keep the barrier to entry for plugin development as low as possible.

**Comment by kek91** [comment]
Absolutely, that'd be great!

**Comment by mherrmann** [comment]
Sneak preview:

![image](https://cloud.githubusercontent.com/assets/1076393/24543261/407f85da-15ff-11e7-8da8-5c8c95855290.png)

Don't know yet if I'll be able to display the number of installs (I currently don't have that information). But it would be awesome.

**Comment by kek91** [comment]
Looks awesome! [Github API provides download_count](https://help.github.com/articles/getting-the-download-count-for-your-releases/), but without having looked into it much yet, I guess only repo contributors/owners have access to get that data

**Comment by mherrmann** [comment]
Eh, that's awesome!!!! Thanks Kim! I've set it to the stars for now

![image](https://cloud.githubusercontent.com/assets/1076393/24544891/5c210c54-1605-11e7-9844-71bbf3cb0bf3.png)

**Comment by raguay** [comment]
Okay. Get everyone that downloads to star it!

**Comment by macosxguru** [comment]
Fantastic. Looks promising.

macosxguru

**Comment by mherrmann** [comment]
This was just released as part of fman 0.3.9 :-) Blog post with detailed info [here](https://fman.io/blog/manage-plugins-inside-fman/).
