### ISSUE TITLE
Empty directories are not copied when copying directory over to directory with same name

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#11]

**Comment by SteveBenner** [comment]
Interestingly I had just found a bug with a plugin that is strikingly similiar... And I'm not quite sure what is going on: https://github.com/klutchnikoff/MoveToOtherPane/issues/2

**Comment by mherrmann** [comment]
I'm sorry but I don't provide support for plugins not created by me.

Regarding the present issue, I can no longer reproduce it. I suspect it was fixed as a part of the fix for #652.

Closing this issue. If someone else can reproduce it, please comment here.
