### ISSUE TITLE
McAffee complains that fman is a trojan

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#14]
![upload_1_18_2017_at_1_20_50_pm](https://cloud.githubusercontent.com/assets/1076393/24148977/4756232a-0e41-11e7-9998-504d433cb551.png)

**Comment by siliconvoodoo** [comment]
anti virus are the trojans. they also complain for any 64 KiB demo of the demoscene (because they are compacted exe). They complain for any wallet of cryptocurrency, they complain even for stuff you are developing yourself sometimes. antivirus -> recycle bin. fixed.

**Comment by mherrmann** [comment]
It's true. Many people, including at large companies, have complained that AV are causing more trouble than they're worth. There was a case for instance where AV was "patching" Chrome to hook into it, and as a result making it _much_ more vulnerable.

Unfortunately, AV is a reality especially in the corporate world. I will have to deal with it.

**Comment by mherrmann** [comment]
After thinking about this, I will no longer treat antivirus tools (except for Microsoft's) marking fman malware as problems of fman. It's their fault, not mine. I wrote up my thoughts in a [blog post](https://fman.io/blog/fman-and-antivirus/).
