### ISSUE TITLE
Windows Defender thinks fman is malware

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#25]
![unnamed](https://cloud.githubusercontent.com/assets/1076393/24149230/0a2d350a-0e42-11e7-8547-f7c606febac4.png)

**Comment by IgorKrupenja** [comment]
Could not reproduce at my end. fman v1.0.0 running as Administrator on Windows 10 Home x64, build 16299.371.

From Windows Defender About window:
Antimalware Client Version: 4.14.17613.18039
Engine Version: 1.1.14800.3
Antivirus Version: 1.267.15.0
Antispyware Version: 1.267.15.0
Network Realtime Inspection Engine Version: 1.1.14800.3
Network Realtime Inspection Signature Version : 1.267.15.0

**Comment by mherrmann** [comment]
So you're saying it's not flagging fman as malware? :)

**Comment by IgorKrupenja** [comment]
No, on my system it does not :) I have also now tried running a custom scan in Windows Defender against `C:/​Users/​<username>/​AppData/​Local/​fman/​` and it found no threats.

**Comment by mherrmann** [comment]
Awesome! :-) It never was a threat of course but antivirus programs have a long history of falsely marking apps as threats, just to be "on the safe side". Thank you for letting me know! I'll mark this issue as closed for now.

**Comment by TrailHacker** [comment]
Just FYI, the issue appears to be back. :( I have never had this issue until now, so maybe they made some changes that brought this back up. I tried opening fman this morning (as usual) and now all of the sudden, Windows Defender said fman is a trojan:

![image](https://user-images.githubusercontent.com/181444/48715163-62f28f80-ebe2-11e8-815f-6fc4962d83fe.png)

**Comment by mherrmann** [comment]
@TrailHacker please see #568.

**Comment by f8ttyc8t** [comment]
Same happens now with version 1.5.6 of fman (where 1.5.5 does not).

**Fixed** as described [here](https://github.com/fman-users/fman/issues/568#issuecomment-438684434). 

Note: required re-installation of fman in my case.

![f-man-ms-defender](https://user-images.githubusercontent.com/1023438/52478677-6fb1ce80-2ba6-11e9-85c4-067159b6d5f3.png)

**Comment by mherrmann** [comment]
@f8ttyc8t also see [this blog post](https://fman.io/blog/fman-and-antivirus/) in case you haven't seen it yet. Nothing of note to A/V has changed in 1.5.6. It's just a pain...

**Comment by f8ttyc8t** [comment]
@mherrmann thanks for additional note. 
MS-Defender behaves strange from time to time, it's a pita sometimes :)
