### ISSUE TITLE
Make path bar editable

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#36]
An alternative solution could simply be to open GoTo on Steroids when the user clicks on the path bar. It has (mostly) the same effect, and includes powerful features for quickly jumping to directories.

_If_ the path bar becomes editable, it would be nice if it auto-completed paths.

Your feedback on this would be appreciated!

**Comment by danmou** [comment]
For me, the biggest benefit of having an editable path bar would be that I could easily copy a specific part, or all, of the current path. This is not possible with the GoTo menu.

**Comment by raguay** [comment]
You can copy part of the path in the GoTo menu. Highlight the entry you are looking for, press tab, and the top bar will be filled in with the complete path. Then copy the part of it you need. I do this all the time. 

Instead of making the path at the top of each panel editable, it might be better to have it open the GoTo menu with the current directory in the search area when clicked. That will keep the main UI as compact as possible and still give a little more flexibility.

**Comment by danmou** [comment]
Thanks @raguay, I hadn't thought about doing it like that. With this in mind I don't see much benefit of an editable path bar, other than maybe that it seems more intuitive to people who are used to traditional file managers. And even then, I think opening the GoTo menu would be just as good.

**Comment by mherrmann** [comment]
Sorry for chiming in so late. I'm working hard on a new file system implementation to support ZIP files etc.

If opening GoTo as disscussed will let you do what you want @Danmou then I think I'll implement it like that. Also because there have been no other suggestions here that would require really making the path bar editable.

**Comment by mbaricevic** [comment]
Hi,
I will really start to use fman after this is resolved (editable path bar).
Best regards, marko.

**Comment by mherrmann** [comment]
Hi Marko, thank you for the feedback. Would it be enough for you if clicking on the path bar opened [GoTo on Steroids](https://fman.io/blog/goto-on-steroids/)?

**Comment by mherrmann** [comment]
@raguay when do you only need to copy _parts of_ the path from GoTo? Instead of the entire path I mean.

**Comment by svlcode** [comment]
Hi Michael,
I have a few different suggestions regarding the use of an editable path bar:
1. Click to navigate to parent folders. See [image](https://i.imgur.com/S9ENROs.png).
2. Type an alias command (like cmd or [cmder](https://github.com/cmderdev/cmder)) to open the terminal  or other apps (like vscode, or sublime) which can the current path. See the [gif](https://i.kinja-img.com/gawker-media/image/upload/s--27P6DPQr--/c_scale,fl_progressive,q_80,w_800/dps1xekz8eyscjw20u3v.gif).

**Comment by mherrmann** [comment]
Hi Vio,

I agree that the "click to navigate to parent folders" is nice. Perhaps eventually, fman will get an implementation like it. But it's more difficult to implement, so for now I'd like to just implement (in fact, already have implemented) the "open GoTo" version.

Regarding your second point, all examples you gave are already possible. To open cmd in the current directory, press <kbd>F9</kbd>. To open a directory in sublime/vscode press <kbd>F4</kbd> on that directory.

**Comment by mherrmann** [comment]
Implemented in [fman 0.9.5](http://fman.io/changelog#v0.9.5).
