### ISSUE TITLE
Treat .zip files like directories

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#37]

**Comment by joshas** [comment]
Support password protected zip archives. When trying to copy or view password protected file - display dialog to enter password.

**Comment by alexpana** [comment]
Perhaps also add support for .tar.gz and other archive formats.

**Comment by mherrmann** [comment]
@alexpana thank you for pointing this out. Support for other formats is captured in [other issues](https://github.com/fman-users/fman/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20treat%20like%20directories%20). If you find a format is still missing, could I ask you to please [create an issue](https://github.com/fman-users/fman/issues/new)?

**Comment by mherrmann** [comment]
Implemented in version 0.7.0, for now without password support. I have created a separate issue for this task (#240).
