### ISSUE TITLE
When fman is already open, "launching" it again doesn't put it in the foreground

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#4]
What seems to happen is that another instance of fman is started, but freezes instantly:

![upload_3_7_2017_at_9_53_09_am](https://cloud.githubusercontent.com/assets/1076393/24148582/c268c876-0e3f-11e7-9a5a-8c69b72e9676.png)

**Comment by mherrmann** [comment]
This seems to be caused by a [bug in PyInstaller](https://github.com/pyinstaller/pyinstaller/issues/2616). Maybe (hopefully) the PyInstaller maintainers will comment on the bug and will help with finding a solution.

**Comment by kszcode** [comment]
Do you know how Sublime is handling this problem?
Are you using the same underlying GUI?

**Comment by mherrmann** [comment]
fman uses a completely different GUI stack from Sublime. (Sublime uses C++ with a custom GUI toolkit while fman uses Python with the Qt framework.) The problem is caused by the [library](https://github.com/pyinstaller/pyinstaller) fman uses to package the Python code as an executable app. If you look at the [library bug](https://github.com/pyinstaller/pyinstaller/issues/2616) I linked to above, you'll see that fixing the problem for fman requires fixing the bug in the library. Knowledge of C and OS X are required to do this. I don't have a lot of experience with this. If someone has that knowledge and would like to fix a bug in an open source library and fman at the same time, that would be awesome. But I'm of course also happy to do this; It just might take me a little longer to get to it.

**Comment by kszcode** [comment]
Thank you! Is there a slack channel regarding python QT framework?

**Comment by mherrmann** [comment]
I don't know, sorry.

**Comment by mherrmann** [comment]
Fixed in fman 0.4.7 :-)
