### ISSUE TITLE
Filter files as you type

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#41]
Say you have

- apple/
- banana.txt
- bananajuice.txt

When you type `p`, only `apple/` should remain in the list of files and `p` should be highlighted. When you then press ESC, all files should be visible again. When you then type `banana`, only `banana.txt` and `bananajuice.txt` should be visible. Pressing Enter opens the currently selected file. Pressing Backspace deletes the last character from the current filter (eg. `banana` -> `banan`). If no filtering is currently taking place (eg. because the user pressed ESC), then Backspace should go up in the directory hierarchy.

This feature is closely related to #40 .

**Comment by mherrmann** [comment]
@kszcode kindly published a plugin that implements functionality very similar to this one: https://github.com/kszcode/FuzzySearchFilesInCurrentFolder

**Comment by mherrmann** [comment]
@rogenaro, you asked for a way (setting/hotkey) to toggle between exact and fuzzy matching (/regex). What exactly do you mean by "exact" and "fuzzy" matching?

**Comment by rogenaro** [comment]
@mherrmann by fuzzy, I meant that we could type `nn` to match both ba**n**a**n**a.txt and ba**n**a**n**ajuice.txt, skipping characters in the filename as long as they exist in the same order typed in our query.

I misused the term "exact", I actually meant subsequent.
In some cases, it would be useful to match only the filenames without skipping, so we would have to type `nan` to match the same files, while `nn` would not match them, but would match a**nn**otation.txt, for example.

In regex  we would just type a regular expression and match the results ( `/^banana*\.txt$/` to get all txt files starting with `banana`, for example )

Depending on the contents of the directory, switching between those modes can be useful and time-saving

**Comment by mherrmann** [comment]
@rogenaro I see, thanks for the clarification :-)

**Comment by EdanMaor** [comment]
This is an incredibly important feature.

I just want to explain one use case I personally care about - let's say I want to move all the jpeg files from a certain folder to another folder. One easy way to do this with filtering is this - I type "jpg", this will display only the jpg files in the current folder. Then I can easily select all (this works only on visible files), then move these using the regular move shortcut.

Of course, the main use case is simply navigating very quickly between folders. To find a sub-folder, I simply start typing its name, then keep typing until it is the only folder left in the list, and hit enter. This is incredibly intuitive and makes navigating *really* fast.

**Comment by mherrmann** [comment]
I agree. The use case you describe is just one of many that makes it important. I'll do my best to get to this feature soon but there are some others that I think are even more important.

**Comment by oskretc** [comment]
+1

**Comment by mherrmann** [comment]
Implemented in [fman 1.3.1](https://fman.io/blog/filter-files-as-you-type/). :tada:

**Comment by oskretc** [comment]
:clap::clap::clap:  
This bring fman from a really nice experiment to super file browser. Kudos on adding this feature.

one thing, maybe add a visual distinctive to the panel to indicate that files are being filtered.

**Comment by mherrmann** [comment]
Thanks! I'm happy to hear you like it. Regarding your suggestion, please file a new issue if you feel it's important. Makes it easier for me to keep track.

**Comment by mherrmann** [comment]
I created the new issue for visual feedback that files are being filtered now: #511.
