### ISSUE TITLE
Context menu support

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#43]
Make it possible to right-click on files, and get a meaningful context menu.

The "basic" implementation could be to display the same menu as the OSs native file manager (eg. Explorer/Finder). However, several users have warned that these context menus tend to be overloaded with entries they don't want; They asked for a "sensible" "reduced" list.

The context menu should also (eventually) be scriptable by plugins. Ideally, already the first implementation (say one which displays the OS's native items) uses fman's plugin API.

**Comment by Taconvino** [comment]
All I need is "extract here" for compressed files and "open with" for anything else.

**Comment by mherrmann** [comment]
@Taconvino it would already be possible to add an "extract here" command. It would just be accessible via the [Command Palette](https://fman.io/docs/shortcuts), not (yet) in a context menu. Would that be of interest to you?

**Comment by Taconvino** [comment]
@mherrmann Oh yes, it would be!  I wouldn't miss pressing the right-click key and just use the command palette for tasks like that, like most things fman.  Is it possible to implement the "open with" command that way too?  I mean, I don't need it to be populated automatically.  I could choose the applications I want to be able to select in that command, like part of a configuration.  Hell, that actually sounds way better than the right click menu in Windows Explorer!

**Comment by mherrmann** [comment]
@Taconvino interesting. I wonder how many other people voted for this issue not so much for being able to right-click, but for the functionality associated with the context menu. I will ask this in a separate reply.

**Comment by mherrmann** [comment]
To people who voted for context menu support in fman: Did you do it because you require a particular feature normally present in that menu, such as `Open with...`? Or did you vote because you truly want to be able to use the right mouse button? Would love to hear your reply @joshas, @albertouri, @nblackburn, @andylima, @hahn-kev, @strangeman, @mousseng, @lsferreira42, @kalons7, @vovcacik, @nozzlegear, @ababak, @kramer3d, @Biegal, @sgarbaciak, @EarMaster, @brodo, @Alexander-Sh, @Kurre, @upiter, @Hammer2900, @kek91, @qwertyda2nd, @rhos, @Danmou, @primaldevelop, @vietzd, @damien122, @elok, @mannp.

**Comment by nblackburn** [comment]
@mherrmann For me, i genuinely think it would make for a good addition.

**Comment by mannp** [comment]
@mherrmann I also think it would be a great addition and am particularly wanting gpg encrypt and decrypt actions, as well as compression and decompress actions.

Currently use Thunar and am hoping fman becomes my full time replacement :)

**Comment by itazitdinov** [comment]
@mherrmann i'm interested in your idea of "basic" implementation(os native fm) as i have a lot of custom actions there. "one commander" got it right in my opinion

**Comment by mherrmann** [comment]
@mannp thx for the reply. So that means it is important to you that you be able to execute those commands with the mouse, correct? Performing the actions with the [Command Palette](https://fman.io/docs/shortcuts) or a keyboard shortcut would be less ideal for you right?

@rhos okay, thanks!

**Comment by mannp** [comment]
@mherrmann I don't want to highjack your design goal as its clear that fman is very keyboard orientated, which is cool.

I use mc in the terminal and when I come out of the terminal I prefer things in the gui.

**Comment by mherrmann** [comment]
@mannp That's fair! Noted. Thanks.

**Comment by kalons7** [comment]
I never use the mouse, but the context menu is also available via the VK_MENU key (on Windows).  And make sure to show at the selection rather than the mouse cursor position in this case.

**Comment by ababak** [comment]
I vote for command palette or both if mouse operations are really important for a lot of people

**Comment by joshas** [comment]
From Windows perspective Total Commander has context menu figured out: it displays default Explorer context menu with some TC commands mixed in (open directory, rename, view, pack). That way you won't need to re-implement all default Explorer options, but it might be a challenge to get them working (shell32 and python).

**Comment by ghost** [comment]
For me the essential is the standard OS context menu... because it brings me (on macOS):
- Open With
- Dropbox commands
- Standard "Share" Menu
- Standard "Services" menu with BetterZip commands, etc.

**Comment by vovcacik** [comment]
Native context menu would be better because I might have installed software and/or shell extensions that I want to access. For example 7z, hash functions, Open with..., mounting ISO natively, mounting VHDX natively etc.

**Comment by sgarbaciak** [comment]
I also voted for native context. It should be more flexible.

**Comment by danmou** [comment]
I don't think there is a native context menu on Linux -- usually it varies depending on the file manager, so they probably each have their own implementation. Anyway these kinds of menus tend to get cluttered with functions you don't need. For me, the best solution would be a customizable context menu that simply shows a list of commands that I can change in the settings (where some items could be shown only when certain types of files are selected).

**Comment by Taconvino** [comment]
I'm not sure how it is on Mac or Linux, but ultimately every context menu option should lead to a shell command with a file path as a parameter (I might be dead wrong here).  At least for me, an alternative for Windows Explorer should include a configurable context menu without resorting to registry hacking.  Command Palette is perfect for this, and should be way easier to configure and extend if needed.

**Comment by vietzd** [comment]
I voted for 'context menu' mostly because I'm missing the features `open with...` and `extract to`.
It would be nice to have a configurable context menu. It's not crucial to open it on rightclick but it would be intuitive.

**Comment by ThePlagueD0ctor** [comment]
I prefer context menu (like standard for current OS) because there is already a collection of useful commands and you don't need to invent them again. I use tortoise svn from context menu. Also time after time you need to get properties of folder/file (to change sharing, attributes, ...). I'd like to have a file manager that can completely replace OS's origin. 
But as other people mentioned here it could be useful to have some commands in pallet or via keyboard shortcuts.

**Comment by siliconvoodoo** [comment]
NEVER GIVE IN to include the OS's standard context menu in fman !
NOT having this, is one of the principal reasons for using another file explorer.
the OS's context menu is bloated by plugins that are called in the forms of dll, this is very unsecure and in the case of, say, tortoise SVN, it breaks often and freezes or crash the whole explorer process. (thus the need for tools like sysinternal's shellex)
I have used other alternative shell explorers, and the one who use the OS context menu, crash on right click.
When users need this, F10 is the way to go.

**Comment by mherrmann** [comment]
@siliconvoodoo I think that's a little too harsh. Some people - see above - would benefit from the default context menu for integrations such as TortoiseSVN etc. I looked into this a few days ago and believe I will offer the OS's context menu in fman. It simply contains some functionality you can't get otherwise. It's what people expect when they right-click. And when someone says their context menu is too bloated, then they can tweak their system (eg. via the registry) to cut down.

**Comment by siliconvoodoo** [comment]
Yes, I need to be harsh on this one because I have a strong opinion. I understand people request as far as the feature is concerned. This is very desirable, but they don't seem to understand the consequence.
If you implement that, please make it opt out in a very sharp way (I want none of the toxicity from this feature at all). If no opt out -> for me it is going to be immediate uninstall of fman.
Think about it this way: I searched google and landed into `fman` because I was not satisfied with windows explorer. And now THE VERY PIECE of windows explorer that got me infuriated in the first place, is going to finds its way back in fman ?

**Comment by mherrmann** [comment]
I love that you are so passionate about this :+1: It's likely the feature will be scriptable via fman's [plugin API](https://fman.io/docs/plugins-introduction). But why is it so important to you to be able to disable it? If you don't like the right-click menu, couldn't you just simply not right-click?

**Comment by danmou** [comment]
I must say I agree with siliconvoodoo on this one. The OS context menu gets quickly bloated and slow, and customizing it is a PITA. Besides, it would ruin the cross-platformness of fman to have a different context menu on each OS. A compromise could be some way of excluding/including specific items from the native context menu through fman's settings.

**Comment by siliconvoodoo** [comment]
@mherrmann thank you. yes my anti-passion for this feature comes from the fact that it is the very presence of this feature that killed it for another explorer (I think xplorer2 lite) it is crashing systematically as soon as you right click. So even if "not right clicking" is an option, it will happen by mistake and cause frustration. And it's going to be a misery for you to support because these complaints are not going to be reproducible on your side, since it's like virtual functions.
Not to mention that windows explorer takes ages to simply display this menu, because it needs to invoke tons of unbound 3rd party dll functions that have no timeout or any sandboxing features.
I like @Danmou 's suggestion of creating a context menu construction GUI where you check the elements you want to import from the OS shell. Make sure it's easy to reset to fail-safe defaults where no elements are inserted in fman.

**Comment by mherrmann** [comment]
@siliconvoodoo if only it were so easy to cherry-pick the elements from the OS shell. I've been researching this for Windows in the past days and simply displaying the default CM is doable. But any customization is painful. Also, how would you configure it? It depends on the kind of file (eg. you may get different suggestions for a PDF than for a JPEG). Etc.

@Danmou thank you for chiming in. I appreciate the discussion because it's a difficult choice to make. Judging from the number of votes, this is fman's most-requested feature right now and it's important to get it right.

Brief summary of what people said so far (I'm also writing this so I can keep track myself):

 * @Taconvino originally looked at the CM for "open with..." and "extract here..." but then said he would actually also be happy if those features were available via the Command Palette. Nevertheless, as a "new user", I think he would have looked at the CM first. Either way, he would like the CM to be configurable.
 * @nblackburn as far as I understood simply wants the OS's native context menu
 * @mannp if I understood correctly likes CM in GUI apps, and the default entries on his OS for encrypt/decrypt and compress/decompress.
 * @rhos simply wants the OS's default CM.
 * @kalons7 wants the features of the default CM even though he accesses it with the keyboard
 * @ababak prefers the Command Palette approach but says mouse support may also be useful for some people.
 * @joshas likes Total Commander's approach of displaying the OS's "default" CM with some extra entries.
 * @andylima and three other people who +1'd his comment really does want macOS's native CM.
 * @vovcacik is in a similar boat and simply wants the native CM (though it sounds like he's on Windows)
 * @sgarbaciak would like a "more flexible" standard CM.
 * @vietzd is in a similar boat as @Taconvino. He only really needs "open with..." and "extract here". He would like it to be configurable.
 * @ThePlagueD0ctor wants the native CM because it includes actions like TortoiseSVN, or changing a file's properties. He added that it would be useful beyond that to have fman commands for (if I understand correctly) doing these things as well.
 * @siliconvoodoo hates the OS's standard CM because it is bloated and crashes often. He says people should use F10 if they need it.
 * @Danmou, you agree with @siliconvoodoo and want a fully customizable non-standard CM. You point out that using the standard CM would make fman less cross-platform. You say that a compromise could be the OS's CM where entries can be "filtered out".

Total
-----

* **Native CM: 11**
  nblackburn, mannp, rhos, kalons7, joshas, andylima (+3), vovcacik, ThePlagueD0ctor
* **Standard but configurable CM: 3**
  Taconvino, sgarbaciak, vietzd
* **Custom CM: 2**
  siliconvoodoo, Danmou
* **Command Palette or both: 1**
  ababak

If I counted the votes correctly, that's a pretty clear lead for an implementation of simply the native CM. I know that is possible for at least Windows. Still have to check the other OSs.

**Comment by Taconvino** [comment]
Just to be clear, I have nothing against a context menu if it's not a mandatory thing. I mean, if "extract here" and "open with" will not be implemented as a command pallette option  because they are part of the context menu I most certainly will be disappointed.

**Comment by nblackburn** [comment]
Whether you make a custom context menu or use the native implementation doesn't matter. If someone makes a plugin, i would expect them to be able to edit the options in it (a zip plugin would likely want to add a zip/extract option for example).

The point of a context menu is to change based on context, if it always shows the same options regardless then it is nothing more than a menu which is not what this issue was created for.

**Comment by mherrmann** [comment]
I conducted further research into how this feature could be implemented - this time on Mac. Unlike Windows, it is not possible to "simply display Finder's context menu for a file". So I will have to implement logic that tries to mimic Finder's behavior as best as possible. The logic will likely have to ask which Services are installed (eg. BetterZip), then display them. Then there are other features in Finder such as the ability to give colored "Tags" to files that a "perfect" copy of Finder's CM would mimic:

![image](https://user-images.githubusercontent.com/1076393/37727078-3d6d8dec-2d37-11e8-8995-000fdebba8cf.png)

Finally, Dropbox's integration is not via macOS's standard means of Services, but (as far as I know) a "hacking of Finder" to extend it:

![image](https://user-images.githubusercontent.com/1076393/37727237-9b67261a-2d37-11e8-8a1e-b92ffeca5465.png)

I'm almost certain that the story will be similar on Linux, where fman won't be able to simply ask the OS to "display the context menu for file X", but will instead have to read system settings to come up with a reasonable list itself.

These results again steer me a little away of simply displaying the standard CM on Windows. Because if I have to implement logic for displaying a custom context menu anyways, I might as well use it on all OS's. I suspect @siliconvoodoo and @Danmou will be happy to hear this (though it's not a final decision yet).

I also still don't understand well enough why people have voted for this issue. In particular, I'm still not certain for many people if they voted because A) their OS's native context menu has a feature that fman is currently lacking or because B) they simply want to use the mouse. The reason that's important is because I might be able to help people in group A) sufficiently by implementing the feature they're missing and exposing it as a normal command via the Command Palette. Eg. @Taconvino said he would be happy if "extract here" were implemented as an fman command; rightclick would only be secondary in this case.

To keep this thread at a manageable complexity, I will try to reach out to everybody who voted by email.

**Comment by MikiGrit** [comment]
As far as I am concerned, I guess I fall within the category A). As I'm currently missing ability to open file in different program than default one.

Also a way to run a simple python script on given file(s) would be nice (similar to Windows "sendto"). I can easily imagine something much more powerful with ability to ask user for additional input after running the script, etc...

**Comment by siliconvoodoo** [comment]
@WestFlame "sendtoscript" would be great. that would allow the community to come up with scripts that do all sorts of fancy stuff. like detect the type, do the most appropriate operation, scan for virus with virus total, diff stuff on multi selection of sources, imagination is the limit...

**Comment by mherrmann** [comment]
@siliconvoodoo @WestFlame running Python scripts on selected files is _exactly_ what [fman's plugin system](https://fman.io/docs/plugins-introduction) does. Check it out!

(I've noted your feedback @WestFlame. I assume you are on Windows.)

**Comment by MikiGrit** [comment]
@mherrmann I'm aware of plugin system but for this purpose, it seems too heavy for each script to have it's own plugin. I imagine some sort of folder with scripts within (although now that I think of it, it could be plugin as a whole :) ).

I'm on Windows and also Linux (Ubuntu).

**Comment by raguay** [comment]
If a full plugin is too heavy, use my plugin 'LaunchScripts' (https://github.com/raguay/LaunchScripts). It allows you to run scripts in any language on your system and sets the environment variables for the different planes and files. Give it a try.

It might be nice to have a menu entry "User Scripts" that shows a sub-menu of each script in the user scripts directory for this plugin. That would be very useful.

**Comment by MikiGrit** [comment]
Wow, that looks like exactly what I thought of :D. Thanks for suggestion.

**Comment by siliconvoodoo** [comment]
@raguay that sounds cool indeed. +1. they could even filter if they want to appear on this extension using a shebang comment.

**Comment by mherrmann** [comment]
An interesting thing that was just pointed out to me via email by a user is that another shortcut to open the context menu on at least Linux (Nautilus) and Windows is <kbd>Shift+F10</kbd> :-)

**Comment by kalons7** [comment]
Yes, I'm aware of that, but I almost always use the dedicated context menu
key since it's more convenient.

**Comment by vovcacik** [comment]
@mherrmann I don't think it is good idea to try to replicate native context menus as you write in your [comment][] above, because it will be very hard to get it right. Just for the Windows you would need to consider:
- extension of the file
- path of the file (e.g. context items in Dropbox folder and subfolders)
- context menu items can be defined in multiple locations
  - in windows registry
  - by calling libraries (7z does it I think)
- context menu can be stateful ([LinkShellExtension][] does it)
- ...more stuff I don't realize right now

Unless you can easily make "give me context menu for X" call I don't think it should be in fman's core as it seems to me that it has potential to become the most complicated and messy part of fman.

[comment]: https://github.com/fman-users/fman/issues/43#issuecomment-375039708
[LinkShellExtension]: http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html

**Comment by vovcacik** [comment]
With the above in mind I was wondering how this sounds to you:

- fman will have his own independent implementation of context menu
- the context menu items would be (mostly or all) commands from Command Palette
- thus the menu is easy to edit (by user or other plugins)
- native context menu will be available through plugins only
  - [purists][] will be happy
  - fallback to native context menu is possible when fman is missing functionality (e.g. [1])
  - on Windows this should be rather easy
  - Mac (possibly Linux) seems to require building the context menu from scratch, which will be complicated
- if there will be native context menu editor it will also be plugin (not an easy one for sure)

It is a compromise, but I as a native context menu supporter would be ok with it as long as the plugins would receive first class support (like fman itself). However the core problem still stands - fallback to native context menu is a must and it won't be easy on all platforms. 

@mherrmann are we really sure the Mac won't let you just pop the context menu for file or dir of your choice?

Feel free to 👍 or 👎 

[purists]: https://github.com/fman-users/fman/issues/43#issuecomment-373282320
[1]: https://github.com/fman-users/fman/issues/43#issuecomment-348558749

**Comment by mherrmann** [comment]
@kalons7 I wrote it because I wasn't aware of it and want to remember ;-)

@vovcacik here's the current state: I was able to email 40 of the 47 people that :+1: or :heart:'d the issue. 25 replied. As you know, I specifically asked "which context menu entries do you need". The most commonly requested commands were very basic: Copy/Cut/Paste, Open (with...), Extract/Compress, Properties. Many of the more special ones (including the ones you and I discussed) would be pretty easy to implement as fman plugins, with the added benefit that they could then also be run from the Command Palette.

You're right that it would likely be very difficult to replicate the native CM exactly. As I wrote above, I think I could simply ask Windows to display its native CM. But I don't think that would be possible on the other OSs. You asked about macOS: [Here](https://stackoverflow.com/a/1871294/1839209) is an answer to your question that says that no, it is not possible to display the native CM. This is also confirmed by the fact that another file manager on macOS which I tested has its own context menu that looks very similar to, but is different from, Finder's CM.

Regarding displaying Windows' native CM as a fallback: Several people in this thread complained that Windows's standard context menu is bloated, slow or crashes. The complexities you pointed out [above](https://github.com/fman-users/fman/issues/43#issuecomment-376213619) also make me believe that displaying Windows's native CM is a can of worms I might not want to open. I really understand people who have custom actions in Explorer's CM that they want to use in fman. But I also need to consider my limited resources and implementing both a "custom" CM _and_ the OS's native one as a fallback sounds like it would take precious time away from other features that are still sorely needed. (PS to anyone who wants to help this, [buy a license](https://fman.io/buy)! fman is still far from being profitable and your support would help tremendously to bring you a better product.)

Given the above, my current inclination is to implement the "independent" CM that you mentioned, but without a "native fallback". I would want the CM to have very similar colors / fonts to the native one though. It would be pretty basic in the beginning. In particular, I'm afraid it would not contain the specialized entries from Dropbox, TortoiseSVN, etc. that I understand people like. But! It would also not be bloated and it can be fully scriptable so everybody can [write a plugin](https://fman.io/docs/plugins-introduction) to add specialized entries.

Thanks for the feedback everyone! Further input is always appreciated.

**Comment by oskretc** [comment]
For those interested in TortoiseSVN support. I've made a simple plugin to interact with TortoiseSVN 

https://github.com/oskretc/fman-tortoisesvnhelper

Hope is helpful

**Comment by mherrmann** [comment]
This is now implemented in [fman 1.0.8](https://fman.io/blog/fmans-new-context-menu/) :tada: I will send out a newsletter about it next week.
