### ISSUE TITLE
Make it possible to filter files by wildcard, eg "*.jpg"

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#56]

**Comment by oskretc** [comment]
+1

**Comment by mherrmann** [comment]
Implemented in [fman 1.3.1](https://fman.io/blog/filter-files-as-you-type/). :tada:

**Comment by keith-hall** [comment]
Is this new filtering functionality exposed in the API at all? I had a quick look but couldn't find it anywhere. I'd like to be able to filter by multiple wildcards, e.g. `*.jpg|*.png` and have a plugin that would allow me to quickly use predefined filters for all "picture files" etc.  Also, if it were part of the API, https://github.com/fman-users/fman/issues/73 could be implemented by a plugin.

**Comment by mherrmann** [comment]
It's currently not part of the API. For a discussion, please see [here](https://github.com/fman-users/fman/issues/512#issuecomment-423422494).

**Comment by mherrmann** [comment]
To be more precise regarding your specific question: I hope the current `DirectoryPane#_add_filter(...)` mentioned in the comment could be made part of the public API and let you do what you want.
