### ISSUE TITLE
fman doesn't realise file size & modified date have changed

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#6]
This happens in many cases:

 - press Shift+F4 to create file, add some content, save: fman still displays "0 bytes"

- Copy two files (eg. `a.txt`, `b.txt` over identically named files with different size/date. fman asks "Do you want to replace a.txt?". Say Yes. fman updates a.txt's size & date. Then prompts "Do you want to replace b.txt?". Say Yes. fman does _not_ update b.txt's size & date

Going up and back down into the same directory doesn't refresh the metadata. Only restarting fman does.

**Comment by Schobers** [comment]
Note that this also happens on Windows

**Comment by mherrmann** [comment]
Noted, thanks.

**Comment by mherrmann** [comment]
The second part of the bug ("copy `a.txt` and `b.txt`...") has been fixed since version 0.7.0. The first part will now also be fixed in upcoming version 0.7.9. The implementation reloads both directory panes whenever fman's window gains focus. This happens when you create a file with Shift+F4, then type some text in your text editor, save, and switch back to fman.
