### ISSUE TITLE
Add a toolbar

### ISSUE THREAD

**Issue by khari3** [fman-users/fman#608]
Sir,

Adding a toolbar is highly essential as it makes the work easier to do,for e.g. without a toolbar if one wants to toggle between details view and thumbnails view how will one do that?
2)Undo file operations also require a toolbar
3)Move back and forth in the details view also require this.

harikrishna

**Comment by kapooostin** [comment]
Does `fman` have `Undo` and `Thumbnail` or `Details` view? And if it were, wouldn't be `Ctrl+Shift-P` enough to call any of these commands?

**Comment by mherrmann** [comment]
No, fman does not currently have Undo, a Thumbnail or a Details view. And yes, as @kapooostin said, `Ctrl+Shift+P` would be enough to call these commands.

I'll close this issue. At the moment, a toolbar would be against fman's focus on minimalism.
