### ISSUE TITLE
An Open With... command

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#61]

**Comment by agateau** [comment]
I created a plugin implementing a basic "Open With" command: https://github.com/agateau/OpenWith, but fman made this a bit harder than expected: for some reason it sets LD_LIBRARY_PATH to /opt/fman, which prevents starting any Qt5-based app on my machine. For this reason the plugin just starts the commands with LD_LIBRARY_PATH unset.

**Comment by mherrmann** [comment]
Looks cool, thanks Aurélien! I found a little bug and filed an issue on your plugin's [issue tracker](https://github.com/agateau/OpenWith/issues).

**Comment by mherrmann** [comment]
P.S.: `LD_LIBRARY_PATH` is set by [PyInstaller](http://www.pyinstaller.org/), the framework which fman uses to turn its Python code into a distributable application. I unfortunately don't think I have much influence on this behaviour.

**Comment by agateau** [comment]
Oh I see. I wonder if it would be possible to unset LD_LIBRARY_PATH after fman has started so that it does not affect plugins. Even better would be to reset it to the value set before fman starts, but that might require some work on PyInstaller itself.

**Comment by mherrmann** [comment]
Hm. It would be worth a try but might be dangerous. What if (for some reason) some library is loaded at a much later stage?

**Comment by agateau** [comment]
That sounds unlikely, but could happen indeed. I don't have a perfect solution for this :/ At least now you are aware of the potential problem.

**Comment by mherrmann** [comment]
Yes, thanks. It's a common problem. In fact, I encountered it in the [Core plugin](https://fman.io/docs/core-plugin) as well. `os_.py` there has:

```
if PLATFORM == 'Linux' and env_not_set and 'LD_LIBRARY_PATH' in os.environ:
	env = os.environ.copy()
	# PyInstaller sets LD_LIBRARY_PATH to /opt/fman.
	# We do not want this to get inherited by child processes!
	del env['LD_LIBRARY_PATH']
```

Maybe I'll just play cowboy and run this code after fman's startup finishes. If the case (which you say is unlikely) where a library is loaded much later does show up, it would at least be easy to fix.

**Comment by mherrmann** [comment]
fman 0.8.6 will unset `LD_LIBRARY_PATH` on Linux to avoid the issue you mentioned @agateau. Let's see if it leads to any unwanted side effects.

**Comment by agateau-g** [comment]
Nice!

**Comment by mherrmann** [comment]
I implemented this feature now in [fman 1.0.2](https://fman.io/changelog#v1.0.2). For details, please see the [associated blog post](https://fman.io/blog/new-open-with-command/). Any feedback would be highly appreciated!

**Comment by agateau** [comment]
Looks good!

**Comment by divenyijanos** [comment]
Is it possible to bind the `open_with` command with a specific app to a keyboard shortcut? I often want to look at several pictures/images at once (in Preview), but if I select them and hit Enter, only the first file is opened. Selecting `Open with...` from Command Palette works (more or less), so it would be great to make it quicker.

**Comment by mherrmann** [comment]
Not yet, but should be easy to implement. I've opened a new [issue](https://github.com/fman-users/fman/issues/436) for this and will tackle it in the next release.
