### ISSUE TITLE
Press Home while renaming file: fman selects first file in directory. Instead, it should move the text cursor to the start of the file name.

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#7]

**Comment by joshas** [comment]
Similar issue is observed in GoTo dialog. Might be in other places too, where single line text is editable.

**Comment by mherrmann** [comment]
Fixed for Rename, will go live with 0.4.3. You're right @joshas that the issue is present in all places where a single line of text is being edited. I've created a new issue for dialogs (#154).

I'm not so sure about GoTo because the default behaviour on Mac is for Home/End to jump to the start/end of lists. What do you think @joshas?

**Comment by joshas** [comment]
I know that there are other key combinations on Mac to quickly jump to start/end of line, but first one I try is Home/End, as I'm used to do on other OS'es. Because GoTo dialog is not a simple input, but something more like terminal prompt + autocomplete - it might not need this particular fix.

**Comment by mherrmann** [comment]
Yes of course you know :) Then I won't implement this for GoTo for now.
