### ISSUE TITLE
Only select name (not the extension) in copy/move dialogs and when renaming files

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#70]

**Comment by kszcode** [comment]
There is a cool feature in Double Commander when you press F2 several times to rename the file.

The first F2 press selects the files with extension. The second press of F2 selects the file name without extension, the third F2 press selects only the extension of the file, the fourth F2 press selects the first word, and so on. It's quite entertaining and useful.

**Comment by mherrmann** [comment]
Interesting @kszcode. The problem is that I don't really know how to accommodate this using fman's current API. The API lets you say "Prompt the user for a value". In the case of renaming files, the "value" is the file name. The present issue could be implemented by letting you also say "Prompt for a value _and_ automatically select a certain part of the default value". Adding support for handling extra shortcuts such as F2 in that dialog would make the implementation a whole lot more complex. I agree it would be a cool implementation, but I'm afraid I'll have to forego it at this point.

**Comment by mherrmann** [comment]
Implemented in [fman 0.7.7](https://fman.io/changelog#v0.7.7).
