### ISSUE TITLE
Cleverly resize columns as fman's window is resized

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#72]
The columns should always fill the available space. The file name column should take up most of it.

**Comment by kszcode** [comment]
It would be good if the date and size would be right aligned.
And the name column would be left aligned with a min-width of: 50em. (characters)

**Comment by Hammer2900** [comment]
this is good feature !

**Comment by mherrmann** [comment]
Fixed. Will be released as part of upcoming version 0.7.0.
