### ISSUE TITLE
Treat .tar files like directories

### ISSUE THREAD

**Issue by mherrmann** [fman-users/fman#80]

**Comment by mherrmann** [comment]
Implemented in [version 0.7.8](https://fman.io/changelog#v0.7.8). Please note that this does not yet add support for `.tar.gz` and `.tar.xz` files. There are separate issues for these archive types (#267 and #268, respectively).

**Comment by neyangg** [comment]
Sorry, but to be honest, I don't like the function of treating something like folder. Because when you do this, there would be more steps to unzip a file. I wonder if there is any way to close this function in the configuration or a byway to unzip conveniently as it used to be, thank you.

**Comment by mherrmann** [comment]
@neyangg: No problem. Please press `Ctrl+Shift+P` (or `Cmd+Shift+P` on Mac) to open the [Command Palette](https://fman.io/docs/shortcuts). Type `List plugins` and confirm with Enter. This should give you another list. Select the `Settings` entry and again confirm with Enter. This should take you to a folder that contains a file `Core Settings (<your OS>).json`. Edit this file by pressing `F4` and add the following entry:

    {
        other settings ...
        , "archive_handlers": {
            ".zip": "zip://",
            ".zipx": "zip://",
            ".jar": "zip://",
            ".xpi": "zip://",
            ".7z": "7z://"
        }
    }

(The comma `,` before the `archive_handlers` entry is important.)

Save the file and use the Command Palette again to execute the command `Reload plugins`. Now, when you press Enter on a `.tar` file, your normal archive handler should open as before.

How does this work? The `archive_handlers` entry which you see above is the same as the one fman normally uses, except without an entry for `.tar` files.

If you have any questions, just let me know :)
