### ISSUE TITLE
Honour your open source promise

### ISSUE THREAD

**Issue by jrappen** [fman-users/fman#820]
## Your promise

You had posted an **open source promise** at:

<https://fman.io/blog/transparency/#open-source-promise>

<details>
<summary>⚠️ CLICK FOR SCREENSHOT</summary>
<img width="872" alt="image" src="https://user-images.githubusercontent.com/8577450/118554994-71de3c80-b762-11eb-8334-e22cbcce42d3.png">
</details>

## Your actions removing references to said promise

Looking at the **Way Back Machine** of the **Internet Archive**:

* after your last commit on [May 3rd 2020](https://web.archive.org/web/20200815110533/https://fman.io/)
* you removed the last commit info from your site on [Oct 3rd 2020](https://web.archive.org/web/20201003041049/https://fman.io/), after realizing 5 months had already passed
* you also changed the licensing model on [Jan 26th 2021](https://web.archive.org/web/20210126204946/https://fman.io/buy/) and later lowered the price on [March 1st 2021](https://web.archive.org/web/20210301001726/https://fman.io/buy/)

You also removed links elsewhere on the site to the [changelog](https://fman.io/changelog) which still shows `v1.7.3` as the current version which was release in May 2020.

## The next step

Please:

* provide download links to the full source code for fman
* open source it under a BSD license
* remove the buy page from your site
* refund customers who bought fman after Nov 3rd 2020

as promised.

---

I assume these fman users frequenting this issue tracker can confirm your promise and my findings: @macosxguru @kek91 @raguay

---

Thanks, have a great day and stay safe.

**Comment by mherrmann** [comment]
Hi, I'm still here and am still maintaining fman. I provide regular fixes and replies to email. And I'm for sure not going to argue with someone who paid me at most 30€. So I'm closing this. It's been discussed before and my stance hasn't changed.
